### ISSUE TITLE
Forge use in github actions example

### ISSUE THREAD

**Issue by alcibiadeseth** [gakonst/foundry#168]
I'd be useful to have a template for using forge to test in a github actions CI pipeline.

**Comment by odyslam** [comment]
Hey @alcibiadeseth, 

It should be very similar to this: https://github.com/gakonst/dapptools-template/blob/master/.github/workflows/ci.yml , but instead of the build steps for `dapptools`, I would use `cargo install` to install this project.

**Comment by gakonst** [comment]
Yeah it'd basically be:
```
      - uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
         with:
          cache-on-failure: true
      - name: Install Foundry
         run: cargo install --git https://github.com/gakonst/foundry --locked
      - name: Run tests
        run: forge test
```
