### ISSUE TITLE
Feature request for example usage and install in github workflow with caching

### ISSUE THREAD

**Issue by alcibiadeseth** [gakonst/foundry#228]
I setup a workflow like so:

```yaml
on:
  push:
    branches:
      - master
  pull_request:

name: Tests

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Install Dependetcies
        run: sudo apt-get install -y libudev-dev

      - name: Install Solidity Compiler Version Manager
        run: cargo install svm-rs

      - name: Install Solidity 0.8.0
        run: svm install 0.8.0

      - name: Install Forge
        run: cargo install --git https://github.com/gakonst/foundry --bin forge --locked

      - name: Use solidity 0.8.0
        run: svm use 0.8.0

      - name: Update libs
        working-directory: ./
        run: forge update

      - name: Run Tests
        working-directory: ./
        run: forge build
```
        
However, this takes far to long to run. It would be nice to have an example of directly pulling the binary artifact for use in a github workflow.
